import { Translations, Language } from './types';

export const translations: Translations = {
  [Language.EN]: {
    pageTitle: "Investment Proposal: 257-Rai Prime Industrial Land",
    logo: "Prime 304 Industrial Land",
    navOverview: "Overview",
    navAsset: "The Asset",
    navLocation: "Location",
    navEcosystem: "Ecosystem",
    navInfrastructure: "Infrastructure",
    navInvestment: "Investment",
    navPrice: "Price",
    navContact: "Contact",
    titleOverview: "Executive Summary",
    textOverview: "This document presents an investment opportunity in a large 257-rai (approx. 41.12 hectares) plot of land, strategically located in Si Maha Phot District, Prachinburi Province. This land holds outstanding potential for development as a regional industrial hub or logistics center. Key advantages include its single-title deed, simplifying the transaction process; its frontage on National Highway 304, a major logistics artery of the country; and its position within a complete industrial ecosystem, surrounded by leading industrial parks like 304 Industrial Park and Rojana Industrial Park. The property is directly connected to Thailand's critical infrastructure, including the Laem Chabang Deep Sea Port, Suvarnabhumi International Airport, and the land border crossing to Cambodia.\n\nFurthermore, the location benefits from being a gateway to the vast labor pool of Northeastern Thailand and is supported by local technical colleges that continuously produce a skilled workforce. This land is not just a property asset but a gateway to markets in Thailand and the Greater Mekong Subregion (GMS), aligning with government investment promotion policies (BOI) and benefiting from the growth of the Eastern Economic Corridor (EEC). This makes it an exceptionally attractive investment proposal for international investors, especially those from China seeking to establish a strong manufacturing and logistics base in Southeast Asia.",
    imgPlaceholder1: "Land Plot Aerial View",
    imgPlaceholder2: "Highway 304 Frontage",
    imgPlaceholder3: "Secondary road that allows large vehicles to pass each other.",
    imgPlaceholder4: "Outline of the overall area",
    titleAsset: "The Investment Asset",
    subtitleAsset1: "Overview and Physical Characteristics",
    textAsset1: "The asset is a large, single-deed land plot totaling 257 rai (approx. 411,200 sq.m.) in Si Maha Phot, Prachinburi, fronting Highway 304. The single-title ownership is a significant advantage for foreign investors, greatly simplifying due diligence and title transfer. The expansive size is suitable for large-scale projects such as a primary manufacturing plant, a major logistics and distribution center, or a boutique industrial park for lease—a rare asset in this rapidly growing industrial corridor.",
    subtitleAsset2: "Unique Topography and Layout",
    textAsset2: "The land has a unique \"elephant\" shape, which is a strategic feature. The \"head and body\" section has 120 meters of direct frontage on Highway 304, serving as the main entrance to the larger ~230-rai area within. The \"tail\" section, a rectangular plot, connects to a secondary public road wide enough for two-way heavy truck traffic. This dual-access layout allows for efficient traffic management, separating logistics flows from employee access and enhancing security for the main internal area.",
    subtitleAsset3: "Development Potential",
    textAsset3: "The plot is ideally suited for industrial or warehouse development, aligning perfectly with the character of the surrounding area, which hosts major industrial estates like 304 Industrial Park and Rojana Industrial Park. The area is zoned for industrial use (\"Purple Zone\"), making it highly probable that permits for factory or warehouse construction will be approved smoothly. Development possibilities include a single-user facility for a large corporation (e.g., automotive assembly, electronics manufacturing) or a multi-tenant industrial park catering to SMEs within the local supply chain.",
    subtitleAsset4: "Zoning and Land Use Compliance",
    textAsset4: "The location within an established industrial corridor, predominantly zoned Purple (industrial/warehouse), strongly indicates a high likelihood of approval for industrial development. While formal verification is a necessary step in due diligence, the surrounding environment provides strong evidence of feasibility, significantly reducing investment risk.",
    titleLocation: "Strategic Location Analysis",
    subtitleLocation1: "Highway 304: The Eastern Logistics Artery",
    textLocation1: "Highway 304 is a nationally significant transport route linking the Bangkok metropolitan area (the economic center) with the Eastern Seaboard (the export manufacturing base) and the Northeast (the country's largest labor source). The property's direct frontage on this highway provides unparalleled connectivity to the national supply chain, eliminating last-mile bottlenecks.",
    viewOnMap: "View on Google Maps",
    subtitleLocation2: "Proximity to Key Economic & Logistics Hubs",
    textLocation2: "The location forms a \"golden triangle\" of logistics connectivity to Thailand's most critical infrastructure: Suvarnabhumi Airport (BKK): The primary air cargo hub. Laem Chabang Deep Sea Port: The country's main export gateway, located in the EEC. Aranyaprathet Border Crossing (Cambodia): A key land route to Cambodia and Vietnam. Bangkok CBD: The nation's financial and commercial heart.",
    subtitleLocation3: "Gateway to the Greater Mekong Subregion (GMS)",
    textLocation3: "Highway 304 is a key part of the GMS economic corridor network, connecting Thailand to Cambodia, Laos, Vietnam, and Southern China. For investors, particularly from China, this positions the asset not just as a base for the Thai market, but as a strategic launchpad into the entire Indochina market, aligning with the Belt and Road Initiative (BRI).",
    titleConnMatrix: "Connectivity Matrix",
    colDest: "Destination",
    colDist: "Approx. Distance (km)",
    colTime: "Approx. Travel Time",
    colImp: "Strategic Importance",
    dest1: "Suvarnabhumi Airport (BKK)",
    time1: "1.5 - 2 Hours",
    imp1: "Asia's Air Cargo Hub",
    dest2: "Laem Chabang Deep Sea Port",
    time2: "2 - 2.5 Hours",
    imp2: "Thailand's Main Export Gateway",
    dest3: "Bangkok CBD",
    time3: "2 - 3 Hours",
    imp3: "Financial & Economic Center",
    dest4: "Aranyaprathet Border",
    time4: "~2 Hours",
    imp4: "Gateway to Cambodia & Vietnam",
    titleEcosystem: "Prachinburi's Industrial Ecosystem",
    subtitleEcosystem1: "Synergy with 304 & Rojana Industrial Parks",
    textEcosystem1: "The property is adjacent to two of Thailand's premier industrial estates: 304 Industrial Park and Rojana Industrial Park. This proximity provides a \"halo effect,\" granting access to a proven ecosystem with established infrastructure, support services, and a history of attracting major foreign investment. Investors benefit from this mature environment without being subject to the specific management fees of those parks.",
    subtitleEcosystem2: "Major Multinational Corporations & Supply Chain Opportunities",
    textEcosystem2: "The area is a dense cluster of global manufacturing giants, particularly in the automotive and electronics sectors. The presence of Tier-1 and Tier-2 suppliers creates immense supply chain synergies. New investors can source high-quality components locally, reducing logistics costs, while new component manufacturers gain immediate access to a large, consolidated customer base.",
    titleMultiNat: "Key Multinational Companies in the Cluster",
    colComp: "Company",
    colNat: "Nationality",
    colInd: "Industry",
    colProd: "Main Products/Services",
    nat1: "Japanese", ind1: "Electronics", prod1: "Semiconductors",
    nat2: "Japanese", ind2: "Electronics", prod2: "Printers, Office Equipment",
    nat3: "Japanese", ind3: "Automotive", prod3: "Stamped Auto Body Parts",
    nat4: "Japanese", ind4: "Automotive", prod4: "Brake Systems, Drivetrains",
    nat5: "US/Japanese", ind5: "Electronics", prod5: "Hard Disk Drives",
    nat6: "US", ind6: "Electronics", prod6: "Automation & Climate Tech",
    nat7: "Japanese", ind7: "Logistics", prod7: "Supply Chain Management",
    nat8: "Thai-Chinese", ind8: "Chemicals", prod8: "Citric Acid, Gypsum",
    titleInfrastructure: "Infrastructure & Human Capital",
    subtitleInfra1: "Utilities (Power, Water, Telecom)",
    textInfra1: "The area is fully serviced with high-stability utilities capable of supporting heavy industry. High-voltage power lines (115KV) are available, and a reliable water supply is provided by both regional and local authorities, with major industrial parks also operating their own reservoirs, ensuring stability.",
    subtitleInfra2: "Labor Market Assessment",
    textInfra2: "The province has a dual advantage: easy access to the vast general labor pool from the Northeast and a ready supply of skilled labor from local vocational colleges (Prachinburi Technical College, etc.). These institutions have long-standing relationships with local industries, tailoring their curricula to meet market demands in fields like mechatronics and industrial management.",
    subtitleInfra3: "Supporting Amenities",
    textInfra3: "The Si Maha Phot area is a well-developed community capable of supporting an expatriate workforce. This includes modern private hospitals (Kasemrad Hospital), international schools (KRIS International School), and community amenities like shopping centers (Big C) and hotels.",
    titleInvestment: "Investment Framework & Growth Catalysts",
    subtitleInvest1: "Board of Investment (BOI) Benefits",
    textInvest1: "As a major industrial hub, projects located here, especially in target industries, are highly likely to qualify for comprehensive incentives from the Thailand Board of Investment (BOI). These benefits often include multi-year corporate income tax exemptions, import duty waivers on machinery, and permissions for foreign land ownership.",
    subtitleInvest2: "Eastern Economic Corridor (EEC) Synergy",
    textInvest2: "While technically outside the three core EEC provinces, the property is adjacent to the EEC and benefits directly from its \"spillover effect.\" As land prices and congestion within the core EEC increase, Prachinburi becomes the most attractive location for expansion, offering lower operational costs while still leveraging the EEC's upgraded infrastructure (ports, airports).",
    subtitleInvest3: "Future Driver: Thai-China High-Speed Rail",
    textInvest3: "The future Thai-China High-Speed Rail project will connect China directly to Thailand via Laos. This will revolutionize regional logistics, drastically cutting transit times. A factory on the Highway 304 corridor will be perfectly positioned to leverage this rail link, transforming it from a Southeast Asian production base into a key node on a new trans-Asian economic corridor directly linked to China's domestic market.",
    contactTitle: "Contact Details",
    titlePrice: "Investment Terms & Offering Price",
    textPrice: "This premier industrial asset is presented with the following investment terms:",
    pricePerRai: "Price per Rai:",
    totalArea: "Total Area:",
    totalPrice: "Total Offering Price:",
    priceNote: "Note: The property is offered as a single lot and will not be subdivided.",
    ariaClose: "Close image viewer",
    ariaNext: "Next image",
    ariaPrevious: "Previous image",
  },
  [Language.TH]: {
    pageTitle: "ข้อเสนอการลงทุน: ที่ดินอุตสาหกรรมศักยภาพสูง 257 ไร่",
    logo: "ที่ดินอุตสาหกรรม 304",
    navOverview: "ภาพรวม",
    navAsset: "สินทรัพย์",
    navLocation: "ทำเล",
    navEcosystem: "ระบบนิเวศ",
    navInfrastructure: "โครงสร้างพื้นฐาน",
    navInvestment: "การลงทุน",
    navPrice: "ราคา",
    navContact: "ติดต่อ",
    titleOverview: "บทสรุปสำหรับผู้บริหาร",
    textOverview: "เอกสารฉบับนี้นำเสนอโอกาสการลงทุนในที่ดินแปลงใหญ่ขนาด 257 ไร่ (ประมาณ 41.12 เฮกตาร์) ซึ่งตั้งอยู่บนทำเลยุทธศาสตร์ในอำเภอศรีมหาโพธิ จังหวัดปราจีนบุรี ที่ดินผืนนี้มีศักยภาพโดดเด่นสำหรับการพัฒนาเป็นศูนย์อุตสาหกรรมหรือคลังสินค้าโลจิสติกส์ระดับภูมิภาค ด้วยจุดเด่นที่สำคัญหลายประการ ได้แก่ การมีโฉนดเพียงฉบับเดียวซึ่งช่วยลดความซับซ้อนในกระบวนการซื้อขาย, การมีหน้ากว้างติดทางหลวงแผ่นดินหมายเลข 304 ซึ่งเป็นเส้นเลือดใหญ่ทางโลจิสติกส์ของประเทศ, และการตั้งอยู่ท่ามกลางระบบนิเวศอุตสาหกรรมที่สมบูรณ์ โดยแวดล้อมไปด้วยนิคมอุตสาหกรรมชั้นนำอย่างสวนอุตสาหกรรม 304 และสวนอุตสาหกรรมโรจนะ ที่ดินแปลงนี้เชื่อมต่อโดยตรงกับโครงสร้างพื้นฐานที่สำคัญของประเทศ ทั้งท่าเรือน้ำลึกแหลมฉบัง สนามบินนานาชาติสุวรรณภูมิ และประตูการค้าชายแดนสู่ประเทศกัมพูชา\n\nนอกจากนี้ ทำเลที่ตั้งยังได้รับประโยชน์จากการเป็นประตูสู่แหล่งแรงงานขนาดใหญ่ของภาคตะวันออกเฉียงเหนือ และได้รับการสนับสนุนจากสถาบันการศึกษาด้านเทคนิคในพื้นที่ซึ่งผลิตบุคลากรที่มีทักษะอย่างต่อเนื่อง ที่ดินแปลงนี้จึงไม่ได้เป็นเพียงสินทรัพย์ที่ดิน แต่เป็นประตูสู่การเข้าถึงตลาดในประเทศไทยและอนุภูมิภาคลุ่มแม่น้ำโขง (GMS) โดยสอดคล้องกับนโยบายส่งเสริมการลงทุนของภาครัฐ (BOI) และได้รับอานิสงส์จากการเติบโตของเขตพัฒนาพิเศษภาคตะวันออก (EEC) ทำให้เป็นข้อเสนอการลงทุนที่น่าสนใจอย่างยิ่งสำหรับนักลงทุนต่างชาติ โดยเฉพาะอย่างยิ่งนักลงทุนจากประเทศจีนที่ต้องการสร้างฐานการผลิตและโลจิสติกส์ที่แข็งแกร่งในภูมิภาคเอเชียตะวันออกเฉียงใต้",
    imgPlaceholder1: "ภาพถ่ายทางอากาศ",
    imgPlaceholder2: "หน้ากว้างติดทางหลวง 304",
    imgPlaceholder3: "ถนนสาธารณะสายรองที่รถบรรทุกขนาดใหญ่สามารถสัญจรสวนกันได้",
    imgPlaceholder4: "เค้าโครงพื้นที่โดยรวม",
    titleAsset: "สินทรัพย์เพื่อการลงทุน",
    subtitleAsset1: "ภาพรวมและลักษณะทางกายภาพ",
    textAsset1: "สินทรัพย์คือที่ดินผืนใหญ่โฉนดเดียวรวม 257 ไร่ (ประมาณ 411,200 ตร.ม.) ใน อ.ศรีมหาโพธิ จ.ปราจีนบุรี ติดทางหลวงหมายเลข 304 การเป็นเจ้าของโฉนดเดียวเป็นข้อได้เปรียบที่สำคัญสำหรับนักลงทุนต่างชาติ ช่วยลดความซับซ้อนในการตรวจสอบสถานะและการโอนกรรมสิทธิ์ ขนาดที่กว้างขวางเหมาะสำหรับโครงการขนาดใหญ่ เช่น โรงงานผลิตหลัก ศูนย์โลจิสติกส์และกระจายสินค้าขนาดใหญ่ หรือสวนอุตสาหกรรมขนาดเล็กสำหรับให้เช่า ซึ่งเป็นสินทรัพย์ที่หาได้ยากในระเบียงอุตสาหกรรมที่เติบโตอย่างรวดเร็วนี้",
    subtitleAsset2: "ลักษณะภูมิประเทศและการจัดวางที่เป็นเอกลักษณ์",
    textAsset2: "ที่ดินมีรูปร่างคล้าย \"ช้าง\" ซึ่งเป็นลักษณะเด่นทางยุทธศาสตร์ ส่วน \"หัวและลำตัว\" มีหน้ากว้าง 120 เมตรติดทางหลวงหมายเลข 304 เป็นทางเข้าหลักสู่พื้นที่ขนาดใหญ่กว่า ~230 ไร่ภายใน ส่วน \"หาง\" ซึ่งเป็นแปลงสี่เหลี่ยมผืนผ้า เชื่อมต่อกับถนนสาธารณะสายรองที่กว้างพอสำหรับรถบรรทุกหนักสองทาง การจัดวางแบบสองทางเข้านี้ช่วยให้การจัดการจราจรมีประสิทธิภาพ แยกการไหลของโลจิสติกส์ออกจากการเข้าถึงของพนักงาน และเพิ่มความปลอดภัยให้กับพื้นที่หลักภายใน",
    subtitleAsset3: "ศักยภาพในการพัฒนา",
    textAsset3: "ที่ดินแปลงนี้เหมาะอย่างยิ่งสำหรับการพัฒนาอุตสาหกรรมหรือคลังสินค้า สอดคล้องกับลักษณะของพื้นที่โดยรอบซึ่งเป็นที่ตั้งของนิคมอุตสาหกรรมขนาดใหญ่ เช่น สวนอุตสาหกรรม 304 และสวนอุตสาหกรรมโรจนะ พื้นที่ถูกจัดเป็นเขตอุตสาหกรรม (\"โซนสีม่วง\") ทำให้มีความเป็นไปได้สูงที่ใบอนุญาตสร้างโรงงานหรือคลังสินค้าจะได้รับการอนุมัติอย่างราบรื่น ความเป็นไปได้ในการพัฒนา ได้แก่ โรงงานสำหรับผู้ใช้รายเดียว (เช่น การประกอบรถยนต์, การผลิตอิเล็กทรอนิกส์) หรือสวนอุตสาหกรรมสำหรับผู้เช่าหลายรายเพื่อรองรับ SMEs ในห่วงโซ่อุปทานท้องถิ่น",
    subtitleAsset4: "การปฏิบัติตามข้อกำหนดผังเมืองและการใช้ประโยชน์ที่ดิน",
    textAsset4: "ที่ตั้งภายในระเบียงอุตสาหกรรมที่จัดตั้งขึ้น ซึ่งส่วนใหญ่เป็นโซนสีม่วง (อุตสาหกรรม/คลังสินค้า) บ่งชี้อย่างชัดเจนถึงความเป็นไปได้สูงที่จะได้รับการอนุมัติสำหรับการพัฒนาอุตสาหกรรม แม้ว่าการตรวจสอบอย่างเป็นทางการจะเป็นขั้นตอนที่จำเป็นในการตรวจสอบสถานะ แต่สภาพแวดล้อมโดยรอบก็เป็นหลักฐานที่ชัดเจนถึงความเป็นไปได้ ซึ่งช่วยลดความเสี่ยงในการลงทุนได้อย่างมาก",
    titleLocation: "การวิเคราะห์ทำเลยุทธศาสตร์",
    subtitleLocation1: "ทางหลวงหมายเลข 304: เส้นเลือดใหญ่โลจิสติกส์ภาคตะวันออก",
    textLocation1: "ทางหลวงหมายเลข 304 เป็นเส้นทางคมนาคมที่สำคัญระดับชาติ เชื่อมต่อเขตกรุงเทพมหานคร (ศูนย์กลางเศรษฐกิจ) กับชายฝั่งทะเลตะวันออก (ฐานการผลิตเพื่อการส่งออก) และภาคตะวันออกเฉียงเหนือ (แหล่งแรงงานที่ใหญ่ที่สุดของประเทศ) การที่ที่ดินติดทางหลวงสายนี้โดยตรงทำให้มีการเชื่อมต่อกับห่วงโซ่อุปทานของประเทศอย่างไม่มีใครเทียบได้ และช่วยขจัดปัญหาคอขวดในระยะสุดท้าย",
    viewOnMap: "ดูบน Google Maps",
    subtitleLocation2: "ความใกล้ชิดกับศูนย์กลางเศรษฐกิจและโลจิสติกส์ที่สำคัญ",
    textLocation2: "ที่ตั้งนี้เป็น \"สามเหลี่ยมทองคำ\" ของการเชื่อมต่อโลจิสติกส์กับโครงสร้างพื้นฐานที่สำคัญที่สุดของประเทศไทย: สนามบินสุวรรณภูมิ (BKK): ศูนย์กลางการขนส่งสินค้าทางอากาศหลัก ท่าเรือน้ำลึกแหลมฉบัง: ประตูส่งออกหลักของประเทศ ตั้งอยู่ใน EEC ด่านพรมแดนอรัญประเทศ (กัมพูชา): เส้นทางบกที่สำคัญสู่กัมพูชาและเวียดนาม ศูนย์กลางธุรกิจกรุงเทพฯ (CBD): หัวใจทางการเงินและพาณิชย์ของประเทศ",
    subtitleLocation3: "ประตูสู่ระเบียงเศรษฐกิจอนุภูมิภาคลุ่มแม่น้ำโขง (GMS)",
    textLocation3: "ทางหลวงหมายเลข 304 เป็นส่วนสำคัญของเครือข่ายระเบียงเศรษฐกิจ GMS ซึ่งเชื่อมโยงประเทศไทยกับกัมพูชา ลาว เวียดนาม และจีนตอนใต้ สำหรับนักลงทุน โดยเฉพาะจากประเทศจีน ที่ตั้งนี้ไม่ได้เป็นเพียงฐานสำหรับตลาดไทย แต่เป็นจุดยุทธศาสตร์ในการเข้าสู่ตลาดอินโดจีนทั้งหมด ซึ่งสอดคล้องกับข้อริเริ่มหนึ่งแถบหนึ่งเส้นทาง (BRI)",
    titleConnMatrix: "ตารางการเชื่อมต่อ",
    colDest: "จุดหมาย",
    colDist: "ระยะทางโดยประมาณ (กม.)",
    colTime: "เวลาเดินทางโดยประมาณ",
    colImp: "ความสำคัญทางยุทธศาสตร์",
    dest1: "สนามบินสุวรรณภูมิ (BKK)",
    time1: "1.5 - 2 ชั่วโมง",
    imp1: "ศูนย์กลางการขนส่งสินค้าทางอากาศของเอเชีย",
    dest2: "ท่าเรือน้ำลึกแหลมฉบัง",
    time2: "2 - 2.5 ชั่วโมง",
    imp2: "ประตูส่งออกหลักของประเทศไทย",
    dest3: "ศูนย์กลางธุรกิจกรุงเทพฯ",
    time3: "2 - 3 ชั่วโมง",
    imp3: "ศูนย์กลางทางการเงินและเศรษฐกิจ",
    dest4: "ด่านพรมแดนอรัญประเทศ",
    time4: "~2 ชั่วโมง",
    imp4: "ประตูสู่กัมพูชาและเวียดนาม",
    titleEcosystem: "ระบบนิเวศอุตสาหกรรมปราจีนบุรี",
    subtitleEcosystem1: "การทำงานร่วมกับสวนอุตสาหกรรม 304 และโรจนะ",
    textEcosystem1: "ที่ดินอยู่ติดกับนิคมอุตสาหกรรมชั้นนำของประเทศไทยสองแห่ง คือ สวนอุตสาหกรรม 304 และสวนอุตสาหกรรมโรจนะ ความใกล้ชิดนี้สร้าง \"ผลกระทบรัศมี\" (halo effect) ทำให้สามารถเข้าถึงระบบนิเวศที่ได้รับการพิสูจน์แล้วซึ่งมีโครงสร้างพื้นฐานที่จัดตั้งขึ้น บริการสนับสนุน และประวัติการดึงดูดการลงทุนจากต่างชาติรายใหญ่ นักลงทุนได้รับประโยชน์จากสภาพแวดล้อมที่สมบูรณ์นี้โดยไม่ต้องเสียค่าธรรมเนียมการจัดการเฉพาะของสวนอุตสาหกรรมเหล่านั้น",
    subtitleEcosystem2: "บริษัทข้ามชาติรายใหญ่และโอกาสทางห่วงโซ่อุปทาน",
    textEcosystem2: "พื้นที่นี้เป็นกลุ่มผู้ผลิตระดับโลกที่หนาแน่น โดยเฉพาะในกลุ่มยานยนต์และอิเล็กทรอนิกส์ การมีอยู่ของผู้ผลิตชิ้นส่วน Tier-1 และ Tier-2 สร้างการทำงานร่วมกันในห่วงโซ่อุปทานอย่างมหาศาล นักลงทุนรายใหม่สามารถจัดหาชิ้นส่วนคุณภาพสูงได้จากในพื้นที่ ซึ่งช่วยลดต้นทุนโลจิสติกส์ ในขณะที่ผู้ผลิตชิ้นส่วนรายใหม่ก็สามารถเข้าถึงฐานลูกค้าขนาดใหญ่ที่รวมตัวกันอยู่ได้ทันที",
    titleMultiNat: "บริษัทข้ามชาติที่สำคัญในคลัสเตอร์",
    colComp: "บริษัท",
    colNat: "สัญชาติ",
    colInd: "อุตสาหกรรม",
    colProd: "ผลิตภัณฑ์/บริการหลัก",
    nat1: "ญี่ปุ่น", ind1: "อิเล็กทรอนิกส์", prod1: "เซมิคอนดักเตอร์",
    nat2: "ญี่ปุ่น", ind2: "อิเล็กทรอนิกส์", prod2: "เครื่องพิมพ์, อุปกรณ์สำนักงาน",
    nat3: "ญี่ปุ่น", ind3: "ยานยนต์", prod3: "ชิ้นส่วนตัวถังรถยนต์ปั๊มขึ้นรูป",
    nat4: "ญี่ปุ่น", ind4: "ยานยนต์", prod4: "ระบบเบรก, ระบบขับเคลื่อน",
    nat5: "สหรัฐฯ/ญี่ปุ่น", ind5: "อิเล็กทรอนิกส์", prod5: "ฮาร์ดดิสก์ไดรฟ์",
    nat6: "สหรัฐฯ", ind6: "อิเล็กทรอนิกส์", prod6: "เทคโนโลยีอัตโนมัติและสภาพอากาศ",
    nat7: "ญี่ปุ่น", ind7: "โลจิสติกส์", prod7: "การจัดการห่วงโซ่อุปทาน",
    nat8: "ไทย-จีน", ind8: "เคมีภัณฑ์", prod8: "กรดซิตริก, ยิปซั่ม",
    titleInfrastructure: "โครงสร้างพื้นฐานและทุนมนุษย์",
    subtitleInfra1: "สาธารณูปโภค (ไฟฟ้า, ประปา, โทรคมนาคม)",
    textInfra1: "พื้นที่นี้มีบริการสาธารณูปโภคที่มีเสถียรภาพสูงครบครัน สามารถรองรับอุตสาหกรรมหนักได้ มีสายส่งไฟฟ้าแรงสูง (115KV) และมีน้ำประปาที่เชื่อถือได้จากทั้งการประปาส่วนภูมิภาคและท้องถิ่น นอกจากนี้ สวนอุตสาหกรรมใหญ่ๆ ยังมีอ่างเก็บน้ำของตนเองเพื่อรับประกันความมั่นคง",
    subtitleInfra2: "การประเมินตลาดแรงงาน",
    textInfra2: "จังหวัดมีข้อได้เปรียบสองด้าน คือ สามารถเข้าถึงแหล่งแรงงานทั่วไปขนาดใหญ่จากภาคตะวันออกเฉียงเหนือได้อย่างง่ายดาย และมีแรงงานมีฝีมือที่พร้อมทำงานจากวิทยาลัยอาชีวศึกษาในพื้นที่ (วิทยาลัยเทคนิคปราจีนบุรี เป็นต้น) สถาบันเหล่านี้มีความสัมพันธ์อันยาวนานกับภาคอุตสาหกรรมในท้องถิ่นและปรับปรุงหลักสูตรให้ตรงกับความต้องการของตลาดในสาขาต่างๆ เช่น เมคคาทรอนิกส์และการจัดการอุตสาหกรรม",
    subtitleInfra3: "สิ่งอำนวยความสะดวกสนับสนุน",
    textInfra3: "พื้นที่ศรีมหาโพธิเป็นชุมชนที่พัฒนาแล้ว สามารถรองรับพนักงานชาวต่างชาติได้ ซึ่งรวมถึงโรงพยาบาลเอกชนที่ทันสมัย (โรงพยาบาลเกษมราษฎร์), โรงเรียนนานาชาติ (KRIS International School), และสิ่งอำนวยความสะดวกในชุมชน เช่น ศูนย์การค้า (บิ๊กซี) และโรงแรม",
    titleInvestment: "กรอบการลงทุนและปัจจัยเร่งการเติบโต",
    subtitleInvest1: "สิทธิประโยชน์จากคณะกรรมการส่งเสริมการลงทุน (BOI)",
    textInvest1: "ในฐานะที่เป็นศูนย์กลางอุตสาหกรรมที่สำคัญ โครงการที่ตั้งอยู่ในพื้นที่นี้ โดยเฉพาะในอุตสาหกรรมเป้าหมาย มีแนวโน้มสูงที่จะได้รับสิทธิประโยชน์ที่ครอบคลุมจากคณะกรรมการส่งเสริมการลงทุน (BOI) ซึ่งมักจะรวมถึงการยกเว้นภาษีเงินได้นิติบุคคลเป็นเวลาหลายปี, การยกเว้นอากรขาเข้าเครื่องจักร, และการอนุญาตให้ต่างชาติถือกรรมสิทธิ์ที่ดินได้",
    subtitleInvest2: "การทำงานร่วมกับระเบียงเศรษฐกิจภาคตะวันออก (EEC)",
    textInvest2: "แม้ว่าจะอยู่นอก 3 จังหวัดหลักของ EEC อย่างเป็นทางการ แต่ที่ดินแปลงนี้ตั้งอยู่ติดกับ EEC และได้รับประโยชน์โดยตรงจาก \"ผลกระทบข้างเคียง\" (spillover effect) ในขณะที่ราคาที่ดินและความแออัดในเขต EEC หลักเพิ่มสูงขึ้น ปราจีนบุรีจะกลายเป็นตัวเลือกที่น่าสนใจที่สุดสำหรับการขยายตัว โดยเสนอต้นทุนการดำเนินงานที่ต่ำกว่า ในขณะที่ยังคงสามารถใช้ประโยชน์จากโครงสร้างพื้นฐานที่ได้รับการยกระดับของ EEC (ท่าเรือ, สนามบิน)",
    subtitleInvest3: "ปัจจัยขับเคลื่อนในอนาคต: รถไฟความเร็วสูงไทย-จีน",
    textInvest3: "โครงการรถไฟความเร็วสูงไทย-จีนในอนาคตจะเชื่อมต่อจีนโดยตรงกับประเทศไทยผ่านทางลาว ซึ่งจะปฏิวัติระบบโลจิสติกส์ของภูมิภาคและลดระยะเวลาการขนส่งลงอย่างมาก โรงงานที่ตั้งอยู่บนระเบียงทางหลวงหมายเลข 304 จะอยู่ในตำแหน่งที่สมบูรณ์แบบที่จะใช้ประโยชน์จากการเชื่อมต่อทางรถไฟนี้ ซึ่งจะเปลี่ยนสถานะจากฐานการผลิตในเอเชียตะวันออกเฉียงใต้ให้กลายเป็นโหนดสำคัญบนระเบียงเศรษฐกิจข้ามเอเชียแห่งใหม่ที่เชื่อมโยงโดยตรงกับตลาดภายในประเทศของจีน",
    contactTitle: "รายละเอียดการติดต่อ",
    titlePrice: "เงื่อนไขการลงทุนและราคาเสนอขาย",
    textPrice: "สินทรัพย์อุตสาหกรรมชั้นนำนี้นำเสนอพร้อมเงื่อนไขการลงทุนดังต่อไปนี้:",
    pricePerRai: "ราคาต่อไร่:",
    totalArea: "พื้นที่ทั้งหมด:",
    totalPrice: "ราคาเสนอขายรวม:",
    priceNote: "หมายเหตุ: ที่ดินเสนอขายเป็นแปลงเดียวทั้งหมด (ไม่แบ่งขาย)",
    ariaClose: "ปิดหน้าต่างดูรูปภาพ",
    ariaNext: "รูปภาพถัดไป",
    ariaPrevious: "รูปภาพก่อนหน้า",
  },
  [Language.ZH]: {
    pageTitle: "投资提案：257莱优质工业用地",
    logo: "304工业用地",
    navOverview: "摘要",
    navAsset: "资产详情",
    navLocation: "战略位置",
    navEcosystem: "工业生态",
    navInfrastructure: "基础设施",
    navInvestment: "投资框架",
    navPrice: "价格",
    navContact: "联系我们",
    titleOverview: "执行摘要",
    textOverview: "本文件旨在介绍一个位于巴真府西玛哈坡县战略位置的大型土地投资机会，该地块面积为257莱（约41.12公顷）。此地块具有发展成为区域性工业中心或物流枢纽的卓越潜力。其主要优势包括：单一地契，简化了交易流程；临近该国主要物流干线304国道；并且地处一个完整的工业生态系统之中，周围环绕着304工业园和洛加纳工业园等领先的工业园区。该地块与泰国的关键基础设施直接相连，包括林查班深水港、素万那普国际机场以及通往柬埔寨的陆路边境口岸。\n\n此外，该地理位置作为通往泰国东北部庞大劳动力资源的门户而受益，并得到当地技术学院的持续支持，这些学院不断培养熟练的劳动力。这块土地不仅仅是一项地产资产，更是进入泰国及大湄公河次区域（GMS）市场的门户，符合政府的投资促进（BOI）政策，并受益于东部经济走廊（EEC）的增长。这使其成为一个对国际投资者，特别是寻求在东南亚建立强大制造和物流基地的中国投资者极具吸引力的投资提案。",
    imgPlaceholder1: "地块鸟瞰图",
    imgPlaceholder2: "304国道临街面",
    imgPlaceholder3: "可供大型车辆双向通行的次级公路",
    imgPlaceholder4: "整体区域轮廓图",
    titleAsset: "投资资产详情",
    subtitleAsset1: "概述和物理特性",
    textAsset1: "该资产为一块大型单一地契地块，总面积257莱（约411,200平方米），位于巴真府西玛哈坡县，临近304国道。单一业权对外国投资者是一个显著优势，极大地简化了尽职调查和所有权转让的流程。其广阔的面积适合大型项目，如主要制造工厂、大型物流配送中心或用于租赁的精品工业园——这在这个快速增长的工业走廊中是稀有资产。",
    subtitleAsset2: "独特的地形和布局",
    textAsset2: "该地块形状独特，形似“大象”，这是一个战略性特征。“头部和身体”部分直接临近304国道，有120米长的临街面，作为通往内部约230莱更大区域的主要入口。“尾部”部分为一矩形地块，连接到一条足以容纳双向重型卡车通行的次级公路。这种双通道布局有助于高效的交通管理，将物料运输与员工出入分开，并增强了主要内部区域的安全性。",
    subtitleAsset3: "开发潜力",
    textAsset3: "该地块非常适合工业或仓库开发，与周边地区（如304工业园和洛加纳工业园等主要工业区的所在地）的特点完美契合。该区域被划为工业用途（“紫色区域”），因此工厂或仓库的建筑许可证很可能会顺利获批。开发可能性包括为大公司（如汽车组装、电子制造）设立的单一用户设施，或为当地供应链中的中小企业服务的可租赁多租户工业园。",
    subtitleAsset4: "区域规划和土地使用合规性",
    textAsset4: "该地块位于一个已建立的工业走廊内，主要被划为紫色区域（工业/仓储），这强烈表明获得工业开发许可的可能性很高。虽然正式核实是尽职调查的必要步骤，但周围环境为项目的可行性提供了有力证据，显著降低了投资风险。",
    titleLocation: "战略位置分析",
    subtitleLocation1: "304国道：东部物流大动脉",
    textLocation1: "304国道是泰国具有国家重要性的交通路线，连接着曼谷都市区（经济中心）、东海岸（出口制造基地）和东北部（该国最大的劳动力来源地）。该地块直接临街这条高速公路，为融入国家供应链提供了无与伦比的连接性，消除了“最后一公里”的瓶颈。",
    viewOnMap: "在谷歌地图上查看",
    subtitleLocation2: "邻近关键经济与物流枢纽",
    textLocation2: "该位置构成了连接泰国最关键基础设施的物流“金三角”：素万那普机场 (BKK): 主要的航空货运枢纽。 林查班深水港: 该国的主要出口门户，位于东部经济走廊（EEC）。 阿兰亚普拉特边境口岸 (柬埔寨): 通往柬埔寨和越南的重要陆路通道。 曼谷中央商务区 (CBD): 国家的金融和商业心脏。",
    subtitleLocation3: "通往大湄公河次区域 (GMS) 的门户",
    textLocation3: "304国道是大湄公河次区域经济走廊网络的重要组成部分，将泰国与柬埔寨、老挝、越南和中国南方连接起来。对于投资者，特别是来自中国的投资者来说，这不仅使该资产成为泰国市场的基地，而且还是进入整个中南半岛市场的战略跳板，与“一带一路”倡议（BRI）相契合。",
    titleConnMatrix: "交通连接矩阵",
    colDest: "目的地",
    colDist: "大约距离 (公里)",
    colTime: "大约车程",
    colImp: "战略重要性",
    dest1: "素万那普机场 (BKK)",
    time1: "1.5 - 2 小时",
    imp1: "亚洲的航空货运枢纽",
    dest2: "林查班深水港",
    time2: "2 - 2.5 小时",
    imp2: "泰国的主要出口门户",
    dest3: "曼谷中央商务区 (CBD)",
    time3: "2 - 3 小时",
    imp3: "金融与经济中心",
    dest4: "阿兰亚普拉特边境",
    time4: "~2 小时",
    imp4: "通往柬埔寨和越南的门户",
    titleEcosystem: "巴真府的工业生态系统",
    subtitleEcosystem1: "与304工业园和洛加纳工业园的协同效应",
    textEcosystem1: "该地块毗邻泰国两个首屈一指的工业区：304工业园和洛加纳工业园。这种邻近性带来了“光环效应”，使得投资者可以进入一个拥有成熟基础设施、支持服务和吸引大量外国投资历史的成熟生态系统。投资者可以从这个成熟的环境中受益，而无需支付这些园区的特定管理费。",
    subtitleEcosystem2: "主要跨国公司与供应链机遇",
    textEcosystem2: "该地区是全球制造业巨头的密集集群，尤其是在汽车和电子行业。一级和二级供应商的存在创造了巨大的供应链协同效应。新投资者可以在本地采购高质量零部件，降低物流成本，而新的零部件制造商则可以立即接触到一个庞大而集中的客户群。",
    titleMultiNat: "集群中的主要跨国公司",
    colComp: "公司",
    colNat: "国籍",
    colInd: "行业",
    colProd: "主要产品/服务",
    nat1: "日本", ind1: "电子", prod1: "半导体",
    nat2: "日本", ind2: "电子", prod2: "打印机、办公设备",
    nat3: "日本", ind3: "汽车", prod3: "冲压汽车车身零件",
    nat4: "日本", ind4: "汽车", prod4: "制动系统、传动系统",
    nat5: "美国/日本", ind5: "电子", prod5: "硬盘驱动器",
    nat6: "美国", ind6: "电子", prod6: "自动化与气候技术",
    nat7: "日本", ind7: "物流", prod7: "供应链管理",
    nat8: "泰中", ind8: "化工", prod8: "柠檬酸、石膏",
    titleInfrastructure: "基础设施与人力资本",
    subtitleInfra1: "公用事业（电力、水、电信）",
    textInfra1: "该地区配备了能够支持重工业的高稳定性公用事业。高压电线（115KV）可用，并由地区和地方当局提供可靠的供水，主要工业园区还运营自己的水库，确保供应稳定。",
    subtitleInfra2: "劳动力市场评估",
    textInfra2: "该省具有双重优势：既容易从东北部获得庞大的普通劳动力，又可以从当地的职业学院（如巴真府技术学院等）获得现成的技术劳动力。这些机构与当地产业有着长期的合作关系，其课程设置（如机电一体化和工业管理）旨在满足市场需求。",
    subtitleInfra3: "配套设施",
    textInfra3: "西玛哈坡地区是一个发展完善的社区，能够支持外籍员工。这包括现代化的私立医院（Kasemrad医院）、国际学校（KRIS国际学校），以及购物中心（Big C）和酒店等社区便利设施。",
    titleInvestment: "投资框架与增长催化剂",
    subtitleInvest1: "投资促进委员会 (BOI) 优惠",
    textInvest1: "作为一个主要的工业中心，设在这里的项目，特别是在目标行业，极有可能获得泰国投资促进委员会（BOI）的全面激励。这些优惠通常包括多年企业所得税豁免、机械进口关税豁免以及允许外商拥有土地所有权。",
    subtitleInvest2: "东部经济走廊 (EEC) 协同效应",
    textInvest2: "尽管地处三个核心EEC省份之外，但该地块紧邻EEC，并直接受益于其“溢出效应”。随着核心EEC区域内土地价格和拥堵程度的增加，巴真府成为最具吸引力的扩张地点，提供更低的运营成本，同时仍能利用EEC升级后的基础设施（港口、机场）。",
    subtitleInvest3: "未来驱动力：中泰高铁",
    textInvest3: "未来的中泰高铁项目将通过老挝直接将中国与泰国连接起来。这将彻底改变区域物流，大幅缩短运输时间。位于304国道走廊的工厂将处于利用这条铁路连接的绝佳位置，将其从一个东南亚生产基地转变为直接与中国国内市场相连的新跨亚洲经济走廊上的一个关键节点。",
    contactTitle: "联系方式",
    titlePrice: "投资条款与报价",
    textPrice: "此优质工业资产的投资条款如下：",
    pricePerRai: "每莱价格：",
    totalArea: "总面积：",
    totalPrice: "总报价：",
    priceNote: "注：该地块为整块出售，不可分割。",
    ariaClose: "关闭图像查看器",
    ariaNext: "下一张图片",
    ariaPrevious: "上一张图片",
  }
};